### ISSUE TITLE
End of stream at input isn’t tested

### ISSUE THREAD

**Issue by arseniiv** [Zabolekar/budivelnyk#2]
Something definite should be happening at EOF when `,` is run, and be tested.

Cf. [https://esolangs.org/wiki/Brainfuck#EOF]():

> EOF is a controversial issue. Many implementations return 0, some return -1, and several notable brainfuck programmers suggest that on EOF the memory cell should be left as-is, without modification. In the original distribution the compiler left the cell unchanged, while the interpreter used the EOF from C which, strictly speaking, could be any negative integer, but which usually is -1 (which, in the case of byte-sized cells, ends up as 255). 

and [https://esolangs.org/wiki/Brainfuck#EOF_2]():

> An interpreter should normally either return Zero or leave the cell unchanged on EOF.
> 
> The Zero option matches the brainfuck language in that the only conditional in brainfuck is a comparison with zero. Using this form, in theory, allows slightly shorter code. For eight bit cells the "leave the cell untouched" matches the C/Unix read(2) system call in that the character memory will be left unchanged on EOF. For Unix the EOF (or error) condition is signalled by the return value, which is lost with BF. If the interpreter's cells are more than eight bits the "unchanged cell" can safely handle binary data. If the cells are eight bit or the interpreter sets the cells to zero on EOF binary data cannot be handled.
> 
> For a brainfuck program this means that ASCII data+EOF should be read using a `[-],` construct (or similar). Binary input should, probably, be read using a construct of the form `[-]-,`. This requires that input bytes are in the range 0..255 when the cell size exceeds eight bits.
> 
> Note: It is strongly recommended that an interpreter be configurable to all three normal form of EOF (Zero, minus one and unchanged).

**Comment by Zabolekar** [comment]
Done, thanks for your comment. The old behaviour was to treat EOF as 255. Now, it's always treated as 0 and `test_bf_to_shared::test_echo` tests it. Minus one doesn't really make sense for our byte-sized cells, and leaving the cell unchanged might be added as an option in the future if there is interest.
